name: Generate Snake Game

on:
  # Run the workflow whenever a commit is pushed to your repo
  push:
    branches:
      - master  # Change to 'main' if your default branch is 'main'
  # Also run it every day at midnight
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Generates the snake game from a GitHub user activity graph
      - name: Generate Snake Game
        uses: Platane/snk@v2
        with:
          # github user name
          github_user_name: YOUR_GITHUB_USERNAME
          # optionnal: display the generated output as a svg instead of a gif
          # gif_out_path: "output/github-contribution-grid-snake.gif"
          svg_out_path: "output/github-contribution-grid-snake.svg"

      # Push the generated image to the repository
      - name: Push Snake Game
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Generate snake animation"
          git push
